openapi: 3.2.0
info:
  title: THANOSQL File API
  description: THANOSQL TEST API documentation
  version: '1.0'
tags:
- name: File
paths:
  /fm/api/v1/contents/{path}:
    get:
      tags:
      - File
      summary: Get
      description: 'Retrieves file/directory information or downloads a file.


        Path parameter

        --------------

        - path: the path to the file/directory relative to the user data root

        (default value is "/", the user data root directory itself)


        Query parameters

        ----------------

        - option: controls the behavior of the API

        - default (None): retrieves file/directory information

        Returns a Content Pydantic object containing information on the target path

        - "download": downloads a file (directory download is not possible)

        Streams the file content or does the download and returns nothing,

        depending on the client request'
      operationId: get_fm_api_v1_contents__path__get
      parameters:
      - required: true
        schema:
          title: Path
          type: string
        name: path
        in: path
      - required: false
        schema:
          title: Option
          type: string
        name: option
        in: query
      - required: false
        schema:
          title: Show Hidden Files
          type: boolean
          default: true
        name: show_hidden_files
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - Bearer Auth: []
    delete:
      tags:
      - File
      summary: Delete
      description: 'Deletes a file or directory permanently.


        Path parameter

        --------------

        - path: the path to the file/directory to be deleted

        relative to the user data root (no default value)


        Return

        ------

        No content (nothing is returned)'
      operationId: delete_fm_api_v1_contents__path__delete
      parameters:
      - required: true
        schema:
          title: Path
          type: string
        name: path
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - Bearer Auth: []
  /fm/api/v1/contents/{destination}:
    post:
      tags:
      - File
      summary: Create
      description: 'Uploads a file or creates an empty folder.


        Path parameter

        --------------

        - destination: the destination path of the upload/folder creation relative to the user data root.

        destination should point to a (would-be) directory, otherwise NotADirectoryError will occur.

        (default value is "/", the user data root directory itself)


        Additional input

        ----------------

        - file: the file to be uploaded (optional)

        - if a file is attached, uploads the file to the destination path

        Returns a Content Pydantic object containing

        information on the file uploaded

        - if no file is attached, creates an empty folder following the destination path

        Returns a Content Pydantic object containing

        information on the newly-created folder'
      operationId: create_fm_api_v1_contents__destination__post
      parameters:
      - required: true
        schema:
          title: Destination
          type: string
        name: destination
        in: path
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_create_fm_api_v1_contents__destination__post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - Bearer Auth: []
  /fm/api/v1/contents/{source}:
    patch:
      tags:
      - File
      summary: Move
      description: 'Moves, renames, or copies a file or directory.


        Path parameter

        --------------

        - source: the path to the file/directory to be moved/renamed/copied

        relative to the user data root (no default value)


        Query parameters

        ----------------

        - destination: the path to the destination file/directory (no default value)

        - option: controls the behavior of the API

        - default (None): moves or renames a file or directory. If the same

        file/directory already exists in the destination, the API behavior

        follows the behavior of Linux file systems.

        Returns a Content Pydantic object containing information on the

        destination file/directory

        - "copy": copies a file or directory. destination should be a directory.

        If the same file/directory already exists in the destination, the

        copied file/directory will be automatically renamed.

        Returns a Content Pydantic object containing information on the

        destination file/directory'
      operationId: move_fm_api_v1_contents__source__patch
      parameters:
      - required: true
        schema:
          title: Source
          type: string
        name: source
        in: path
      - required: true
        schema:
          title: Destination
          type: string
        name: destination
        in: query
      - required: false
        schema:
          title: Option
          type: string
        name: option
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - Bearer Auth: []
  /fm/api/v1/size/:
    get:
      tags:
      - File
      summary: Get Size
      operationId: get_size_fm_api_v1_size__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Size'
      security:
      - Bearer Auth: []
components:
  schemas:
    Size:
      title: Size
      type: object
      properties:
        max_size:
          title: Max Size
          type: integer
          default: 0
        used_size:
          title: Used Size
          type: integer
          default: 0
        avail_size:
          title: Avail Size
          type: integer
          default: 0
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ContentInfo:
      title: ContentInfo
      type: object
      properties:
        name:
          title: Name
          type: string
          default: ''
        format:
          title: Format
          type: string
        path:
          title: Path
          type: string
          default: ''
        type:
          title: Type
          type: string
          default: file
        size:
          title: Size
          type: integer
        writable:
          title: Writable
          type: boolean
          default: true
        content:
          title: Content
        created_at:
          title: Created At
          type: string
          format: date-time
          default: '0001-01-01T00:00:00'
        updated_at:
          title: Updated At
          type: string
          format: date-time
          default: '0001-01-01T00:00:00'
    Body_create_fm_api_v1_contents__destination__post:
      title: Body_create_fm_api_v1_contents__destination__post
      type: object
      properties:
        file:
          title: File
          type: string
          format: binary
    Content:
      title: Content
      type: object
      properties:
        content_info:
          title: Content Info
          allOf:
          - $ref: '#/components/schemas/ContentInfo'
          default:
            name: ''
            path: ''
            type: file
            writable: true
            created_at: '0001-01-01T00:00:00'
            updated_at: '0001-01-01T00:00:00'
        root:
          title: Root
          type: string
          default: /home/jovyan
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
  securitySchemes:
    Bearer_Auth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Enter: **''Bearer &lt;JWT&gt;''**, where JWT is the access token. Example: Bearer access_token_comes_here'
