openapi: 3.2.0
info:
  title: THANOSQL View API
  description: THANOSQL TEST API documentation
  version: '1.0'
tags:
- name: View
paths:
  /api/v1/view/:
    get:
      tags:
      - View
      summary: Get Views
      description: 'Gets the paginated list of all the views from the given schema. If no

        schema is provided then the function retreives all of the views from

        all of the schemas. pg_catalog and information_schema related views are

        exempted, unless specified. The API can only return 100 views at a time,

        starting from the offset number specified.


        Parameters

        ----------

        - schema : str, default None

        The schema to retrieve the views from. If None is

        provided, refers to all schemas.

        - verbose: bool, default False

        Whether to include only base information or verbose information on the views.

        - offset: int, default 0

        The offset position of where to select the views from.

        - limit: int, default 100

        The number of views to retrieve. This value must range from 0 and 100.


        Returns

        -------

        A ViewsResponse Pydantic object containing a List of

        either View Pydantic or Base Table Pydantic models depending

        on the verbose parameter.'
      operationId: get_views_api_v1_view__get
      parameters:
      - required: false
        schema:
          title: Schema
          type: string
        name: schema
        in: query
      - required: false
        schema:
          title: Verbose
          type: boolean
          default: false
        name: verbose
        in: query
      - required: false
        schema:
          title: Offset
          type: integer
          default: 0
        name: offset
        in: query
      - required: false
        schema:
          title: Limit
          type: integer
          default: 100
        name: limit
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - Bearer Auth: []
  /api/v1/view/{view_name}:
    get:
      tags:
      - View
      summary: Get View
      description: 'Gets the View object with the specified view_name and

        schema. If the schema is not specified, it automatically

        defaults to public.


        Parameters

        ----------

        view_name: str

        schema : str, default public

        The schema to retrieve the views from. If no parameter is

        provided, assigned as public.


        Returns

        -------

        A ViewResponse Pydantic object containing a View Pydantic object.'
      operationId: get_view_api_v1_view__view_name__get
      parameters:
      - required: true
        schema:
          title: View Name
          type: string
        name: view_name
        in: path
      - required: false
        schema:
          title: Schema
          type: string
          default: public
        name: schema
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - Bearer Auth: []
    delete:
      tags:
      - View
      summary: Delete View
      description: 'Deletes the view specified by view_name and schema.


        Parameters

        ----------

        - view_name: str

        - schema : str, default "public"

        The schema to delete the view from. If no parameter is

        provided, defaults to "public".


        Returns

        -------

        A ViewMessage Pydantic object containing a success message and the view_name.'
      operationId: delete_view_api_v1_view__view_name__delete
      parameters:
      - required: true
        schema:
          title: View Name
          type: string
        name: view_name
        in: path
      - required: false
        schema:
          title: Schema
          type: string
          default: public
        name: schema
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewMessageResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - Bearer Auth: []
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ViewResponse:
      title: ViewResponse
      required:
      - view
      type: object
      properties:
        view:
          $ref: '#/components/schemas/View'
    ViewMessageResponse:
      title: ViewMessageResponse
      required:
      - message
      - view_name
      type: object
      properties:
        message:
          title: Message
          type: string
        view_name:
          title: View Name
          type: string
    View:
      title: View
      required:
      - definition
      type: object
      properties:
        name:
          title: Name
          type: string
        schema:
          title: Schema
          type: string
        columns:
          title: Columns
          type: array
          items:
            $ref: '#/components/schemas/Column'
        definition:
          title: Definition
          type: string
    Column:
      title: Column
      required:
      - type
      - name
      type: object
      properties:
        id:
          title: Id
          type: integer
        default:
          title: Default
          type: string
        is_nullable:
          title: Is Nullable
          type: boolean
          default: true
        type:
          title: Type
          type: string
        name:
          title: Name
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
  securitySchemes:
    Bearer_Auth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Enter: **''Bearer &lt;JWT&gt;''**, where JWT is the access token. Example: Bearer access_token_comes_here'
